framework:
    default_locale: '%locale%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - 'en'

# php_translation
translation:
    locales: '%locales_array%'
    default_locale: '%locale%'
    webui:
        enabled: true
    edit_in_place:
        enabled: false
        config_name: site
    configs:
        site:
            dirs: ["%kernel.project_dir%/public/theme/%bolt.theme%"]
            output_dir: "%kernel.project_dir%/translations"
    auto_add_missing_translations:
        enabled: true
        config_name: site
