parameters:
  locale: en
  app_locales: en|nl|es|fr|de|pl|it|hu|pt_BR|ja|nb|nn|nl_NL|nl_BE|is|ru|cs|bg
  app.notifications.email_sender: anonymous@example.com
  bolt.table_prefix: bolt_
  bolt.backend_url: /bolt
  bolt.remember_lifetime: 2592000
  bolt.doctrine_behaviors_translatable_fetch_mode: LAZY
  bolt.doctrine_behaviors_translation_fetch_mode: LAZY
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $locales: '%app_locales%'
      $defaultLocale: '%locale%'
      $emailSender: '%app.notifications.email_sender%'
      $projectDir: '%kernel.project_dir%'
      $publicFolder: '%bolt.public_folder%'
      $tablePrefix: '%bolt.table_prefix%'
      $backendUrl: '%bolt.backend_url%'
      $rememberLifetime: '%bolt.remember_lifetime%'
  _instanceof:
    Bolt\Menu\ExtensionBackendMenuInterface:
      tags: [bolt.extension_backend_menu]
  App\:
    resource: '../src/*'
    exclude:
      - ../src/DependencyInjection/
      - ../src/Entity/
      - ../src/Exception/
      - ../src/Kernel.php
  Bolt\:
    resource: '../vendor/bolt/core/src/*'
    exclude: '../vendor/bolt/core/src/{Entity,Exception,Kernel.php}'
  Bolt\Api\Extensions\ContentExtension:
    tags:
      - { name: api_platform.doctrine.orm.query_extension.collection }
      - { name: api_platform.doctrine.orm.query_extension.item }
  Bolt\Controller\:
    resource: ../vendor/bolt/core/src/Controller
    tags:
      - controller.service_arguments
  Bolt\Doctrine\TablePrefix:
    tags:
      - { name: doctrine.event_listener, event: loadClassMetadata, lazy: true }
  Bolt\Event\Listener\ContentFillListener:
    tags:
      - { name: doctrine.event_listener, event: postLoad }
      - { name: doctrine.event_listener, event: prePersist }
      - { name: doctrine.event_listener, event: preUpdate }
  Bolt\Event\Listener\FieldFillListener:
    tags:
      - { name: doctrine.event_listener, event: preUpdate }
  Bolt\Event\Listener\FieldDiscriminatorListener:
    tags:
      - { name: doctrine.event_listener, event: loadClassMetadata }
  Bolt\Event\Listener\TaxonomyFillListener:
    tags:
      - { name: doctrine.event_listener, event: postLoad }
  Bolt\Event\Listener\UserAvatarLoadListener:
    tags:
      - { name: doctrine.event_listener, event: postLoad }
  Bolt\Event\Listener\TranslatableListener:
    arguments:
      $translatableFetchMode: '%bolt.doctrine_behaviors_translatable_fetch_mode%'
      $translationFetchMode: '%bolt.doctrine_behaviors_translation_fetch_mode%'
    tags:
      - { name: doctrine.event_listener, event: loadClassMetadata }
      - { name: doctrine.event_listener, event: postLoad }
      - { name: doctrine.event_listener, event: prePersist }
  Bolt\Extension\RoutesLoader:
    tags:
      - routing.loader
  Bolt\Menu\BackendMenuBuilder:
    arguments:
      - '@knp_menu.factory'
      - !tagged_iterator bolt.extension_backend_menu
    tags:
      - { name: knp_menu.menu_builder, method: createAdminMenu, alias: admin_menu }
  Bolt\Cache\RelatedOptionsUtilityCacher:
    decorates: Bolt\Utils\RelatedOptionsUtility
  Bolt\Cache\CanonicalCacher:
    decorates: Bolt\Canonical
  Bolt\Cache\SelectOptionsCacher:
    decorates: Bolt\Twig\FieldExtension
  Bolt\Cache\ContentToArrayCacher:
    decorates: Bolt\Twig\JsonExtension
  Bolt\Cache\GetFormatCacher:
    decorates: Bolt\Utils\ContentHelper
  Bolt\Cache\FilesIndexCacher:
    decorates: Bolt\Utils\FilesIndex
  Bolt\Menu\BackendMenuBuilderInterface: '@Bolt\Menu\BackendMenu'
  Bolt\Menu\FrontendMenuBuilder: ~
  Bolt\Menu\FrontendMenuBuilderInterface: '@Bolt\Menu\FrontendMenu'
  Bolt\Storage\ContentQueryParser:
    calls:
      - { method: addService, arguments: [select, '@Bolt\Storage\SelectQuery'] }
  Bolt\Storage\Query:
    calls:
      - { method: addScope, arguments: [frontend, '@Bolt\Storage\FrontendQueryScope'] }
  Bolt\Twig\DumpExtension:
    arguments:
      - '%kernel.environment%'
  Bolt\Validator\ContentValidatorInterface: '@Bolt\Validator\ContentValidator'
  Bolt\Utils\Sanitiser:
    public: true
  Doctrine\ORM\Query\Expr: ~
  monolog.processor.request:
    class: Bolt\Log\RequestProcessor
    tags:
      - { handler: db, method: processRecord, name: monolog.processor }
  Symfony\Bridge\Twig\Extension\AssetExtension: '@twig.extension.assets'
  Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'
  Symfony\Component\ErrorHandler\ErrorRenderer\ErrorRendererInterface: '@error_handler.error_renderer.html'
  Squirrel\TwigPhpSyntax\PhpSyntaxExtension: ~
  Twig\Extension\StringLoaderExtension: ~
  twig.extension.pcre:
    class: Jasny\Twig\PcreExtension
    tags:
      - { name: twig.extension }
  twig.extension.text:
    class: Jasny\Twig\TextExtension
    tags:
      - { name: twig.extension }
  twig.extension.array:
    class: Jasny\Twig\ArrayExtension
    tags:
      - { name: twig.extension }
  Bolt\Api\ContentProcessor:
    bind:
      $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'
      $removeProcessor: '@api_platform.doctrine.orm.state.remove_processor'
